# Generated by Django 5.2.15 on 2026-06-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collection_method',
            field=models.CharField(choices=[('personal_transfer', 'Personal mobile money'), ('integrated', 'Merchant API'), ('stripe', 'Stripe')], default='personal_transfer', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
