# Generated by Django 5.2.15 on 2026-06-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='collection_tier',
            field=models.CharField(choices=[('personal', 'Personal number only (no merchant account)'), ('merchant', 'Registered business / merchant account')], default='personal', max_length=20),
        ),
    ]
