# Generated by Django 5.2.15 on 2026-06-24 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_reconciliation_and_personal_collection'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('sms_paste', 'SMS pasted'), ('manual', 'Manual entry'), ('buyer_claim', 'Buyer reported payment'), ('api', 'Provider API')], max_length=20)),
                ('status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched to order'), ('disputed', 'Disputed')], default='unmatched', max_length=20)),
                ('raw_sms', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('txn_reference', models.CharField(blank=True, max_length=64)),
                ('payer_phone', models.CharField(blank=True, max_length=20)),
                ('parse_confidence', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('parsed_fields', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='marketplace.order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
